# Generated by Django 2.2.4 on 2020-09-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_metadata', '0002_auto_20170125_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicefieldbase',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='textfieldbase',
            options={'base_manager_name': 'objects'},
        ),
    ]
